### ISSUE TITLE
Write a draft of "New Hires On-boarding Checklist"

### ISSUE THREAD

**Issue by zspencer** [zincmade/employee-handbook#4]
Maybe something like? 

- [ ] Filled in info: https://docs.google.com/a/zincma.de/spreadsheets/d/1MGZJidkiasWWA98JugD6kmvRG1i66XOavelLs050D_k/edit#gid=0
- [ ] Has slack access
- [ ] Part of all-internal google group
- [ ] Re-invite all-internal to the shared folders to refresh access permissions
- [ ] Signed employee handbook
- [ ] Signed employee agreement
- [ ] Filled in I-9
- [ ] Uploaded proof of identity + legality to work to private Drive folder
